# Generated by Django 3.2 on 2023-11-05 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=100, verbose_name='EMail Id')),
                ('password', models.TextField(max_length='100', verbose_name='Password')),
                ('firstname', models.CharField(default='', max_length=100, verbose_name='FirstName')),
                ('lastname', models.CharField(default='', max_length=100, verbose_name='LastName')),
                ('authToken', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 11, 5, 12, 37, 29, 516293))),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
    ]
